M48
; DRILL file KiCad 10.0.3-10.0.3~ubuntu26.04.1 date 2026-06-04T12:47:01
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-04T12:47:01+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3-10.0.3~ubuntu26.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X4.0Y36.0
X4.0Y4.0
X46.0Y36.0
X46.0Y4.0
M30
